### ISSUE TITLE
Max Dimension Limit For Web Full Quality?

### ISSUE THREAD

**Issue by tomtom215** [firebase/friendlypix#35]
I've only found information documenting setting max height or width in the input=image/* categories but i assume 1280 = 1280x720 in this uploader.js static function referrs to?

Also, since the image is drawn to canvas, and uses polyfills for blobs, I was hitting some issues where an iPhone image capture would fail during upload once i raised the max dimensions and was wondering if you had suggested max's if I was looking to capture a full resolution image.

(from uploader.js)
![image](https://cloud.githubusercontent.com/assets/4908716/18332884/2a3e21ea-7538-11e6-85d7-0b35a9518a29.png)

**Comment by nicolasgarnier** [comment]
Hey @tomtom215,

It's likely your upload was failing because of the Firebase Storage rule where we limit the size of images to 1MB for thumbnails and 5MB for full sized image.

This is set in https://github.com/firebase/friendlypix/blob/master/web/storage.rules

You'd have to change that if you want to allow full sized images upload.

**Comment by tomtom215** [comment]
@nicolasgarnier thank you so much for your help!!
